# Downloaded from https://github.com/autopkg/homebysix-recipes/blob/26f97759822c6c90b8f458f35b82ff9496785c71/Docker/DockerDesktop.munki.recipe
# Commit: 26f97759822c6c90b8f458f35b82ff9496785c71
# Downloaded at: 2025-11-27 22:26:26 UTC

Comment: Created with Recipe Robot v2.2.1 (https://github.com/homebysix/recipe-robot)
Description: Downloads the latest version of Docker Desktop and imports it into Munki. See the download recipe description for information about using the PLATFORM_ARCH input variable to download the Intel/Apple Silicon version of Docker.
Identifier: com.github.homebysix.munki.DockerDesktop
Input:
  MUNKI_REPO_SUBDIR: apps/%NAME%
  NAME: Docker
  pkginfo:
    catalogs:
    - testing
    description: Automates deployment of containerized applications.
    developer: Docker
    display_name: Docker
    name: '%NAME%'
    unattended_install: true
    unattended_uninstall: true
MinimumVersion: 1.4.1
ParentRecipe: com.github.homebysix.download.DockerDesktop
Process:
- Processor: MunkiImporter
  Arguments:
    pkg_path: '%pathname%'
    repo_subdirectory: '%MUNKI_REPO_SUBDIR%'
