# Downloaded from https://github.com/autopkg/homebysix-recipes/blob/26f97759822c6c90b8f458f35b82ff9496785c71/Docker/DockerDesktop.install.recipe
# Commit: 26f97759822c6c90b8f458f35b82ff9496785c71
# Downloaded at: 2025-11-27 22:26:26 UTC

Comment: Created with Recipe Robot v2.2.1 (https://github.com/homebysix/recipe-robot)
Description: Installs the latest version of Docker Desktop. See the download recipe description for information about using the PLATFORM_ARCH input variable to download the Intel/Apple Silicon version of Docker.
Identifier: com.github.homebysix.install.DockerDesktop
Input:
  NAME: Docker
MinimumVersion: 1.4.1
ParentRecipe: com.github.homebysix.download.DockerDesktop
Process:
- Processor: InstallFromDMG
  Arguments:
    dmg_path: '%pathname%'
    items_to_copy:
    - destination_path: /Applications
      source_item: Docker.app
